// Listes complètes pour les formulaires d'inscription

export const UNIVERSITIES_TOGO = [
  // Universités publiques
  "Université de Lomé",
  "Université de Kara",
  "École Normale Supérieure",
  "École Supérieure de Gestion",
  "École Nationale d'Administration",
  "École Supérieure d'Agronomie",
  "École Supérieure des Sciences de la Santé",
  "Institut Supérieur de Formation aux Métiers de l'Éducation",
  "Institut Supérieur de Technologie",
  
  // Universités privées
  "Université Catholique de l'Afrique de l'Ouest",
  "Institut Africain d'Administration et d'Études Commerciales",
  "École Supérieure de Commerce et de Gestion",
  "Institut Supérieur des Métiers du Numérique",
  "Université Privée de Lomé",
  "ESTIM - École Supérieure de Technologie et d'Innovation du Management",
  "ESGIS - École Supérieure de Gestion, d'Informatique et des Sciences",
  "ISCOM - Institut Supérieur de Communication",
  "ISCAM - Institut Supérieur de Commerce et d'Administration des Entreprises",
  "UCAO-UUT - Université Catholique de l'Afrique de l'Ouest",
  "IAEC - Institut Africain d'Études Commerciales",
  "HETEC - École Supérieure de Technologie",
  "ENSAE - École Nationale de la Statistique et de l'Économie Appliquée",
  "ENSI - École Nationale Supérieure d'Ingénieurs",
  "ESTMT - École Supérieure des Techniques et Métiers du Textile",
  "ESGE - École Supérieure de Gestion et d'Économie",
  "ISFOP - Institut Supérieur de Formation Professionnelle",
  "UNILOMÉ - Université Privée de Lomé",
  "CAMPUS FSEF - Campus Francophone de Formation et d'Études Supérieures",
  "EAMAU - École Africaine des Métiers de l'Architecture et de l'Urbanisme",
  "ESAE - École Supérieure d'Administration des Entreprises",
  "ESISTEL - École Supérieure d'Informatique et de Télécommunications",
  "ESCAE - École Supérieure de Commerce et d'Administration des Entreprises",
  "ISMA - Institut Supérieur des Métiers de l'Audiovisuel",
  "EFSI - École de Formation Supérieure en Informatique",
  "IFODEP - Institut de Formation et de Développement Professionnel",
  "CNAM - Conservatoire National des Arts et Métiers",
  "ESAG - École Supérieure d'Administration et de Gestion",
  "ESTC - École Supérieure de Technologie et de Commerce",
  "ISCT - Institut Supérieur de Commerce et de Technologie",
  "ESEF - École Supérieure d'Économie et de Finance",
  "ESMT - École Supérieure des Métiers et Technologies",
  "IFAD - Institut de Formation et d'Appui au Développement",
  "CESTI - Centre d'Études des Sciences et Techniques de l'Information",
  "ESIPE - École Supérieure d'Ingénierie et de Physique Électronique",
  "ISTM - Institut Supérieur de Technologie et de Management",
  "ESCG - École Supérieure de Commerce et de Gestion",
  "ISEG - Institut Supérieur d'Études de Gestion",
  "ESTIA - École Supérieure de Technologie et d'Innovation Appliquée",
  "IFPG - Institut de Formation Professionnelle et de Gestion",
  "ESCOM - École Supérieure de Communication"
];

export const STUDY_FIELDS_TOGO = [
  // Informatique et Technologies
  "Informatique",
  "Génie Logiciel",
  "Systèmes d'Information",
  "Télécommunications",
  "Réseaux et Sécurité",
  "Intelligence Artificielle",
  "Développement Web",
  "Développement Mobile",
  "Cybersécurité",
  "Data Science",
  "Électronique",
  "Électrotechnique",
  "Automatique",
  "Génie Industriel",
  
  // Commerce et Gestion
  "Commerce",
  "Gestion",
  "Management",
  "Administration des Entreprises",
  "Marketing",
  "Ressources Humaines",
  "Finance",
  "Comptabilité",
  "Audit",
  "Contrôle de Gestion",
  "Logistique",
  "Supply Chain",
  "Entrepreneuriat",
  "Commerce International",
  "Économie",
  "Économie Numérique",
  "Banque et Finance",
  "Assurance",
  "Immobilier",
  "Tourisme et Hôtellerie",
  
  // Droit et Sciences Politiques
  "Droit",
  "Droit des Affaires",
  "Droit International",
  "Sciences Politiques",
  "Administration Publique",
  "Relations Internationales",
  "Diplomatie",
  "Gouvernance",
  
  // Communication et Médias
  "Communication",
  "Journalisme",
  "Relations Publiques",
  "Communication Digitale",
  "Audiovisuel",
  "Cinéma",
  "Photographie",
  "Design Graphique",
  "Multimédia",
  "Publicité",
  
  // Santé et Sciences Médicales
  "Médecine",
  "Pharmacie",
  "Dentaire",
  "Infirmier",
  "Sage-femme",
  "Kinésithérapie",
  "Laboratoire",
  "Radiologie",
  "Santé Publique",
  "Nutrition",
  
  // Éducation et Formation
  "Sciences de l'Éducation",
  "Formation des Formateurs",
  "Pédagogie",
  "Psychologie",
  "Psychologie Clinique",
  "Sociologie",
  "Anthropologie",
  "Philosophie",
  "Histoire",
  "Géographie",
  "Lettres Modernes",
  "Linguistique",
  "Langues Étrangères",
  "Anglais",
  "Français",
  "Allemand",
  "Espagnol",
  "Chinois",
  
  // Agriculture et Environnement
  "Agronomie",
  "Zootechnie",
  "Foresterie",
  "Environnement",
  "Développement Durable",
  "Écologie",
  "Génie Rural",
  "Agroalimentaire",
  "Pêche et Aquaculture",
  "Météorologie",
  
  // Sciences Exactes
  "Mathématiques",
  "Physique",
  "Chimie",
  "Biologie",
  "Statistiques",
  "Recherche Opérationnelle",
  "Actuariat",
  "Géologie",
  "Géophysique",
  "Géomatique",
  
  // Art et Culture
  "Arts Plastiques",
  "Musique",
  "Danse",
  "Théâtre",
  "Littérature",
  "Culture",
  "Patrimoine",
  "Mode et Textile",
  "Artisanat",
  
  // Architecture et Urbanisme
  "Architecture",
  "Urbanisme",
  "Génie Civil",
  "Bâtiment et Travaux Publics",
  "Topographie",
  "Aménagement du Territoire",
  
  // Transport et Logistique
  "Transport",
  "Logistique",
  "Aviation",
  "Maritime",
  "Automobile",
  "Maintenance",
  
  // Énergie et Mines
  "Énergie",
  "Énergies Renouvelables",
  "Mines",
  "Pétrole et Gaz",
  "Génie Minier",
  "Génie Pétrolier",
  
  // Social et Humanitaire
  "Travail Social",
  "Développement Social",
  "Coopération Internationale",
  "Humanitaire",
  "Droits de l'Homme",
  "Genre et Développement",
  
  // Sport et Loisirs
  "Sport",
  "Éducation Physique",
  "Management Sportif",
  "Kinésithérapie du Sport",
  "Loisirs et Tourisme",
  
  // Autre
  "Autre"
];

export const STUDY_LEVELS = [
  "Licence 1 (L1)",
  "Licence 2 (L2)",
  "Licence 3 (L3)",
  "Master 1 (M1)",
  "Master 2 (M2)",
  "Doctorat",
  "BTS 1",
  "BTS 2",
  "DUT 1",
  "DUT 2",
  "Autre"
];

export const CONTRACT_TYPES = [
  "Stage",
  "Temps partiel",
  "Temps plein",
  "CDI",
  "CDD",
  "Freelance",
  "Consultation",
  "Bénévolat",
  "Apprentissage",
  "Autre"
];

export const LOCATIONS_TOGO = [
  "Lomé",
  "Sokodé",
  "Kara",
  "Atakpamé",
  "Kpalimé",
  "Tsévié",
  "Aného",
  "Vogan",
  "Badou",
  "Bassar",
  "Kandé",
  "Mango",
  "Dapaong",
  "Niamtougou",
  "Bafilo",
  "Tchamba",
  "Notsé",
  "Tabligbo",
  "Aneho",
  "Amlamé",
  "Autre"
];

export const COMPANY_SECTORS = [
  "Technologie",
  "Informatique",
  "Télécommunications",
  "Finance",
  "Banque",
  "Assurance",
  "Immobilier",
  "Santé",
  "Pharmaceutique",
  "Médical",
  "Éducation",
  "Formation",
  "Recherche",
  "Commerce",
  "Retail",
  "E-commerce",
  "Distribution",
  "Industrie",
  "Manufacturing",
  "Automobile",
  "Aéronautique",
  "Énergie",
  "Pétrole et Gaz",
  "Énergies renouvelables",
  "Construction",
  "BTP",
  "Architecture",
  "Agriculture",
  "Agroalimentaire",
  "Tourisme",
  "Hôtellerie",
  "Restauration",
  "Transport",
  "Logistique",
  "Média",
  "Communication",
  "Publicité",
  "Marketing",
  "Conseil",
  "Audit",
  "Ressources Humaines",
  "Juridique",
  "Administration publique",
  "ONG",
  "Association",
  "Fondation",
  "Sport",
  "Culture",
  "Divertissement",
  "Autre"
];

export const COMPANY_SIZES = [
  "1-10 employés",
  "11-50 employés",
  "51-200 employés",
  "201-500 employés",
  "500+ employés"
];
